name: publish package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
      # Checkout repo and setup python deps
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install needed deps
        run: >-
          pip install setuptools wheel twine

      # Build the package w correct version from tag
      - name: Extract the github tagname
        run: export CVPARTNER_PY_VERSION="${GITHUB_REF#refs/*/}"
      - name: Build package
        run: >-
          ./setup.py sdist bdist_wheel

      # Publish the package to PyPI
      - name: Write login to file
        run: >-
          echo "${{ secrets.PYPI_CVPARTNERPY_REPO_LOGIN }}" > $HOME/.pypirc
      - name: publish to PyPi
        run:
          ./setup.py publish
